<a href="https://colab.research.google.com/github/OlaseeniOlayinka/CSCI-561/blob/main/Homework0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
import collections

In [35]:
salaries = pd.read_csv(r"Salaries.csv")

In [9]:
salaries = salaries.set_index('playerID')
salaries

yearID teamID lgID    salary
playerID                               
barkele01    1985    ATL   NL    870000
bedrost01    1985    ATL   NL    550000
benedbr01    1985    ATL   NL    545000
campri01     1985    ATL   NL    633333
ceronri01    1985    ATL   NL    625000
...           ...    ...  ...       ...
treinbl01    2015    WAS   NL    512800
ugglada01    2015    WAS   NL    507500
werthja01    2015    WAS   NL  21000000
zimmejo02    2015    WAS   NL  16500000
zimmery01    2015    WAS   NL  14000000

[25575 rows x 4 columns]

In [14]:
salaries = salaries.drop('bedrost01', axis = 0)

In [27]:
atlHouPlayers = salaries[['teamID','salary']]
atlPlayers = atlHouPlayers[atlHouPlayers['teamID'] == 'ATL']
houPlayers = atlHouPlayers[atlHouPlayers['teamID'] == 'HOU']
atl_hou = pd.concat([atlPlayers, houPlayers], axis = 0)


In [29]:
atlPlayers.describe()

salary
count  8.820000e+02
mean   2.213354e+06
std    3.438817e+06
min    6.000000e+04
25%    3.000000e+05
50%    6.000000e+05
75%    2.437500e+06
max    1.606180e+07

In [34]:
rich_players = atlHouPlayers[atlHouPlayers['salary'] > 1000000]
rich_players.index  #playerID

Index(['hornebo01', 'murphda05', 'suttebr01', 'lynnfr01', 'murraed02',
       'stanlbo01', 'decindo01', 'jacksre01', 'cruzju01', 'seaveto01',
       ...
       'rendoan01', 'scherma01', 'spande01', 'stammcr01', 'storedr01',
       'strasst01', 'thornma01', 'werthja01', 'zimmejo02', 'zimmery01'],
      dtype='object', name='playerID', length=9456)

In [38]:
salary_dict = collections.defaultdict(list)

for key in salaries:
  for value in salaries[key]:
    salary_dict[key].append(value)

In [52]:
salary_dict = atl_hou.to_dict('list')
#salary_dict['teamID']

In [56]:
pd.DataFrame(salary_dict)

teamID   salary
0       ATL   870000
1       ATL   545000
2       ATL   633333
3       ATL   625000
4       ATL   800000
...     ...      ...
1730    HOU  2000000
1731    HOU  2400000
1732    HOU   512900
1733    HOU  1000000
1734    HOU  4200000

[1735 rows x 2 columns]

In [54]:
atl_hou.head()

teamID  salary
playerID                
barkele01    ATL  870000
benedbr01    ATL  545000
campri01     ATL  633333
ceronri01    ATL  625000
chambch01    ATL  800000

In [1]:
#salary_dict

In [8]:
a = [[1, 2, 3], [4, 5, 6]]
a = np.array(a)

In [9]:
print(a.ndim, a.shape, a.size, a.dtype, a.itemsize, a.data)

2 (2, 3) 6 int64 8 <memory at 0x7f4e0aba6050>


In [14]:
a = np.reshape(a, (3,2))
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [15]:
print(a.flatten())

[1 2 3 4 5 6]


In [18]:
#slicing
print(a[0:2], a[0:2][1], a[1][1:])

[[1 2]
 [3 4]] [3 4] [4]


In [35]:
''' argmin(), argmax(), min(), max(), mean(), sum(), std(), dot(), square(), sqrt(),
 abs(). exp(), sign(), and mod()arange(), ones(), zeros(), eye(), linspace(), concatenate'''

#argmin
print('for columns, ', np.argmin(a, axis = 0))
print('for rows, ', ' ', np.argmin(a, axis = 1))
print(np.max(a), np.min(a))

print(np.sum(a), np.mean(a))
print(np.std(a)) # standard deviation
print(np.dot(a, np.random.randint(6, size = (2,3))))
print(np.square(a))
print(np.sqrt(a))
print(np.zeros(6))

for columns,  [0 0]
for rows,    [0 0 0]
6 1
21 3.5
1.707825127659933
[[ 7  2 12]
 [19  4 26]
 [31  6 40]]
[[ 1  4]
 [ 9 16]
 [25 36]]
[[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]]
[0. 0. 0. 0. 0. 0.]


In [ ]:
#matplotlib
